### ISSUE TITLE
The "healthPractitioner" Field Returns Null On populate()

### ISSUE THREAD

**Issue by asaddc** [VaccTrax-Project-Organization/Vacctrax#30]
http://localhost:3000/api/getAllAppointmentsByPatientId/605e313002e8ba38a71c700c

![image](https://user-images.githubusercontent.com/12679129/112707582-e98a9c00-8e82-11eb-82af-bb836f530a6a.png)

In the appointments.server.controller.js file: 
![image](https://user-images.githubusercontent.com/12679129/112707621-18a10d80-8e83-11eb-835f-3cc9fa9ec02e.png)

I'm passing the appropriate data to retrieve the healthPractitioner info, yet I am still having it returned as null... I have no clue why.

**Comment by Razei** [comment]
Fixed in #41
